#!/usr/bin/env bash

if which pcregrep &>/dev/null; then
  find "$@" -type f \
  | pcregrep -v '/\.[^/]*$' \
  | pcregrep -v '\$\.[^/]*$' \
  | xargs chmod -R 755
else
  find "$@" -type f \
  | xargs chmod -R 755
fi
